apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadgsax2234-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadgsax2234-tenant-component
    app.kubernetes.io/part-of: loadgsax2234-tenant-app
  name: loadgsax2234-tenant-component
  namespace: loadgsax2234-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: loadgsax2234-tenant-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: loadgsax2234-tenant-component
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/test-images:0291f245117a40c3b2d22c661e48c27d
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
