apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadgsax2234-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadgsax2234-tenant-component
    app.kubernetes.io/part-of: loadgsax2234-tenant-app
  name: loadgsax2234-tenant-component
  namespace: loadgsax2234-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadgsax2234-tenant-component
status:
  loadBalancer: {}
